# Generated by Django 4.1.1 on 2025-07-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('batch', models.CharField(choices=[('morning', 'Morning Batch'), ('afternoon', 'Afternoon Batch'), ('evening', 'Evening Batch'), ('weekend', 'Weekend Batch')], max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
