# Generated by Django 4.1.1 on 2025-07-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exelapp', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dates', models.DateField()),
                ('intime', models.CharField(max_length=100, null=True)),
                ('outtime', models.CharField(max_length=100, null=True)),
                ('staff', models.CharField(max_length=100, null=True)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
