# Generated by Django 4.1.1 on 2025-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exelapp', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
